version: '3'

services:
  form:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    #volumes:
    #  - ./app:/app
    #command: npm run form.js
    #restart: always